# Generated by Django 4.1.1 on 2022-11-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': ('Region',),
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='SectorsModel',
            fields=[
                ('sector_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=100, unique=True)),
                ('sector_description', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': ('Sector',),
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='EmployerModel',
            fields=[
                ('employer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employer_name', models.CharField(max_length=100, unique=True)),
                ('tin', models.CharField(max_length=100)),
                ('short_code', models.CharField(max_length=20)),
                ('postal_address', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_address', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_position', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_email', models.CharField(blank=True, max_length=100, null=True)),
                ('vote_code', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('control_number', models.BigIntegerField(blank=True, null=True)),
                ('vote_no', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.IntegerField(choices=[(1, 'PUBLIC EMPLOYERS'), (2, 'CENTRAL GOVERMENT EMPLOYERS'), (3, 'PRIVATE EMPLOYERS')], default=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authenticationApp.regionmodel')),
                ('sectors', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authenticationApp.sectorsmodel')),
            ],
            options={
                'verbose_name': ('Employer',),
                'verbose_name_plural': 'Employers',
            },
        ),
    ]
