# Generated by Django 4.1.1 on 2022-11-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercategory',
            name='employer_category_must_have_an_employer',
        ),
        migrations.RemoveConstraint(
            model_name='usercategory',
            name='benef_category_must_have_a_benef',
        ),
    ]
