# Generated by Django 4.1.1 on 2022-10-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employermodel',
            name='id',
        ),
        migrations.AddField(
            model_name='employermodel',
            name='employer_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
