# Generated by Django 4.1.1 on 2022-11-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0002_remove_usercategory_employer_category_must_have_an_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='beneficiary', to='authenticationApp.beneficiarymodel'),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employer', to='authenticationApp.employermodel'),
        ),
    ]
