# Generated by Django 4.1.1 on 2022-11-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0003_alter_usercategory_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employermodel',
            name='employer_code',
            field=models.CharField(default='001', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DistrictsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticationApp.regionmodel')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'tbl_districts',
            },
        ),
    ]
