# Generated by Django 4.1.1 on 2022-11-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0004_employermodel_employer_code_districtsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOfficerModel',
            fields=[
                ('officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role_id', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name': ('LoanOfficer',),
                'verbose_name_plural': 'LoanOfficers',
                'db_table': 'tbl_loan_officers',
            },
        ),
        migrations.RenameField(
            model_name='beneficiarymodel',
            old_name='isLoanee',
            new_name='is_loanee',
        ),
    ]
