# Generated by Django 4.1.1 on 2022-11-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0007_rename_officer_id_loanofficermodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanofficermodel',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
