# Generated by Django 4.1.1 on 2022-11-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0008_alter_loanofficermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanofficermodel',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
