# Generated by Django 4.1.1 on 2022-11-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0009_alter_loanofficermodel_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanofficermodel',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
