# Generated by Django 4.1.1 on 2022-11-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0010_alter_loanofficermodel_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanofficermodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='loanofficermodel',
            name='role',
            field=models.CharField(choices=[('LO', 'HLI Loan Officer'), ('LAO', 'Loan Allocation Officer'), ('SLAO', 'Senior Loan Allocation Officer'), ('MLO', 'Manager Loan Allocation Officer'), ('ADLA', 'Assistant Director Loan Allocation'), ('ADLD', 'Assistant Director Loan Disbursement'), ('LDO', 'Loan Disbursement Officer'), ('SLDO', 'Senior Loan Disbursement Officer'), ('MLD', 'Manager Loan Disbursement')], max_length=30),
        ),
    ]
